server:
  port: 9001

spring:
  application:
    name: paper-service
  devtools:
    livereload:
      enabled: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : ${EUREKA_DEFAULT_ZONE}